### ISSUE TITLE
Virtual-hyperscript aliases for better experience

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-web#16]
`div({class: 'container', style: {background: 'red'}}, [ span('Hello World') ])` 
equivalent to 
`h('div.container', {style: {background: 'red'}}, [ h('span', 'Hello World') ])`

**Comment by ohanhi** [comment]
I am working on exactly this sort of a library. The idea is that you can use the library as a plugin, feeding it the hyperscript implementation you need - in this case the `virtual-hyperscript`. It is very early stages, but if you are willing to wait a bit, it might make sense for you not to include the functionality in Cycle.

https://github.com/ohanhi/hyperscript-helpers

**Comment by staltz** [comment]
Great stuff. I think I'll just point people to your library instead of putting this inside Cycle Web, because many prefer JSX based on virtual-hyperscript, so it's good if the alternative hyperscript helper isn't mandatory to download with Cycle Web.

**Comment by staltz** [comment]
Note to self: put library as utility on https://github.com/vic/awesome-cyclejs when it's ready

**Comment by ohanhi** [comment]
@staltz https://www.npmjs.com/package/hyperscript-helpers

**Comment by staltz** [comment]
Cewl
